Tie post endpoint with frontend
techswitch-learners/WhaleSpottingJuly pull request #26
Opened 2021-08-05 11:32 UTC by IlyasAli1

https://trello.com/c/VXdDADar

2021-08-05 15:01 UTC, oskarwilliams378 requested changes

2021-08-05 15:01 UTC, oskarwilliams commented on WhaleSpotting.UnitTests/Controllers/SightingControllerTests.cs
> +using Microsoft.Extensions.Options;
Do we need this?

2021-08-05 15:01 UTC, oskarwilliams commented on WhaleSpotting.UnitTests/Controllers/SightingControllerTests.cs
> +            var validationProblemDetails = validationErrorResult.Subject.Value as ValidationProblemDetails;
```suggestion
            var validationErrorResult = response.Should().BeOfType<ObjectResult>().Subject;
            var validationProblemDetails = validationErrorResult.Value.Should().BeOfType<ValidationProblemDetails>().Subject;
```

2021-08-05 15:01 UTC, oskarwilliams commented on WhaleSpotting/Controllers/SightingsController.cs
> +    //[ValidateModel]
Commented code

2021-08-05 15:01 UTC, oskarwilliams commented on WhaleSpotting/Controllers/SightingsController.cs
> +                ModelState.AddModelError("Thrown Error", e.Message);
```suggestion
                ModelState.AddModelError(nameof(SightingRequestModel.SightedAt), e.Message);
```
We know what this error is on, so we should say that in the key

2021-08-05 15:01 UTC, oskarwilliams commented on WhaleSpotting/Controllers/SightingsController.cs
> +
New lines

2021-08-05 15:01 UTC, oskarwilliams commented on WhaleSpotting/react-app/src/components/ReportSighting.tsx
> +export function ShowResultMessage({ responseMessage } : any): JSX.Element {
This should be in another component :) Then both can be export default. Also we should have an interface for the props

2021-08-05 15:01 UTC, oskarwilliams378 commented on WhaleSpotting/react-app/src/components/ReportSighting.tsx
> +        if (isError) {
new line before this please :)

2021-08-05 15:01 UTC, oskarwilliams378 commented on WhaleSpotting/react-app/src/apiModels/CreateSightingApiModel.ts
> +    sightedAt: Date | undefined;
Should this be allowed to be undefined?

2021-08-06 09:25 UTC, OPTIMIMCOW commented on WhaleSpotting.UnitTests/Controllers/SightingControllerTests.cs
> +using Microsoft.Extensions.Options;
Addressed.

2021-08-06 09:27 UTC, OPTIMIMCOW commented on WhaleSpotting.UnitTests/Controllers/SightingControllerTests.cs
> +            var validationProblemDetails = validationErrorResult.Subject.Value as ValidationProblemDetails;
Addressed.

2021-08-06 09:28 UTC, OPTIMIMCOW commented on WhaleSpotting/Controllers/SightingsController.cs
> +    //[ValidateModel]
Addressed.

2021-08-06 09:28 UTC, OPTIMIMCOW commented on WhaleSpotting/Controllers/SightingsController.cs
> +                ModelState.AddModelError("Thrown Error", e.Message);
Addressed.

2021-08-06 09:29 UTC, OPTIMIMCOW commented on WhaleSpotting/Controllers/SightingsController.cs
> +
Addressed.

2021-08-06 09:29 UTC, OPTIMIMCOW commented on WhaleSpotting/react-app/src/components/ReportSighting.tsx
> +        if (isError) {
Addressed.

2021-08-06 09:31 UTC, OPTIMIMCOW commented on WhaleSpotting/react-app/src/apiModels/CreateSightingApiModel.ts
> +    sightedAt: Date | undefined;
Addressed.

2021-08-09 09:00 UTC, oskarwilliams378 requested changes

2021-08-09 09:00 UTC, oskarwilliams commented on WhaleSpotting/react-app/src/components/ShowResultMessage.tsx
> +    return <div></div>;
```suggestion
    return responseMessage 
        ? <p data-testid="response-result" className="response-message-card">
            {responseMessage}
        </p>
        : <div/>;
}
```

2021-08-09 09:00 UTC, oskarwilliams378 commented on WhaleSpotting/react-app/src/styles/Buttons.scss
> +    height:50px;
space before value pls

2021-08-09 09:00 UTC, oskarwilliams378 commented on WhaleSpotting/react-app/src/styles/Buttons.scss
> +    height:unset;
here too

2021-08-09 09:08 UTC, OPTIMIMCOW commented on WhaleSpotting/react-app/src/components/ReportSighting.tsx
> +export function ShowResultMessage({ responseMessage } : any): JSX.Element {
Addressed.

2021-08-09 09:57 UTC, IlyasAli1 commented on WhaleSpotting/react-app/src/components/ShowResultMessage.tsx
> +    return <div></div>;
Done

2021-08-09 09:58 UTC, IlyasAli1 commented on WhaleSpotting/react-app/src/styles/Buttons.scss
> +    height:50px;
Done

2021-08-09 09:58 UTC, IlyasAli1 commented on WhaleSpotting/react-app/src/styles/Buttons.scss
> +    height:unset;
Done

2021-08-09 14:19 UTC, oskarwilliams378 approved these changes

2021-08-09 15:16 UTC, merged